Get it to the point of successful extraction onto disk

diff --git a/image-client b/image-client
--- a/image-client
+++ b/image-client
@@ -81,7 +81,7 @@ usage()
 # Constants.
 # image="image.img"
 image="image.tar.gz"
-image_type="${image##.}"
+image_type="${image#*.}"
 image_gpg="${image}.sig"
 
 wget_args="-t 5 -T 30 --progress=dot"
@@ -122,7 +122,7 @@ done
 
 
 # Runtime variables.
-tmp_dir=$(mktemp -d "${name}.XXXXXXXXXX")
+tmp_dir=$(mktemp -p "/tmp" -d "${name}.XXXXXXXXXX")
 
 
 # Startup logging.
@@ -172,12 +172,26 @@ then
 elif [ "${image_type}" = "tar.gz" ]
 then
     log_info "installing image using mkfs/tar"
+
+    log_debug "creating filesystem on device '${partition_b}'"
     mkfs -t "${mkfs_type}" "${partition_b}"
+
+    log_debug "making directory '${tmp_dir}/root'"
+    mkdir -p "${tmp_dir}/root"
+
+    log_debug "mounting device '${partition_b}' at '${tmp_dir}/root'"
     mount -t "${mkfs_type}" "${partition_b}" "${tmp_dir}/root"
-    tar -zxf "${tmp_dir}/${image}" "${tmp_dir}/root"
+
+    log_debug "extracting contents of '${tmp_dir}/${image}' to '${tmp_dir}/root'"
+    tar -C "${tmp_dir}/root" -zxf "${tmp_dir}/${image}"
+
+    log_debug "unmounting device '${partition_b}'"
     umount -l "${tmp_dir}/root"
+else
+    log_error_exit 1 "invalid value '${image_type}' for image_type"
 fi
 
+exit 0
 
 # update-grub
 # /etc/default/grub for Debian/Ubuntu
@@ -192,7 +206,7 @@ GRUB_DEFAULT=${grub_default_b}
 GRUB_HIDDEN_TIMEOUT=0
 GRUB_HIDDEN_TIMEOUT_QUIET=true
 GRUB_TIMEOUT=10
-GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
+GRUB_DISTRIBUTOR=\`lsb_release -i -s 2> /dev/null || echo Debian\`
 GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
 GRUB_CMDLINE_LINUX=""
 
@@ -206,7 +220,7 @@ GRUB_CMDLINE_LINUX=""
 
 # The resolution used on graphical terminal
 # note that you can use only modes which your graphic card supports via VBE
-# you can see them in real GRUB with the command `vbeinfo'
+# you can see them in real GRUB with the command \`vbeinfo'
 #GRUB_GFXMODE=640x480
 
 # Uncomment if you don't want GRUB to pass "root=UUID=xxx" parameter to Linux
