Add logic, argument handling and logging

diff --git a/image-client b/image-client
--- a/image-client
+++ b/image-client
@@ -6,18 +6,124 @@ shopt -s failglob
 
 
 name="image-client"
+version="1.0.0"
 
+
+###
+###
+###
+
+
+log_critical()
+{
+    [ $verbosity -ge 1 ] && echo "[CRITICAL] $@" 1>&2 || true
+}
+
+
+log_error()
+{
+    [ $verbosity -ge 2 ] && echo "[ERROR] $@" 1>&2 || true
+}
+
+
+log_warning()
+{
+    [ $verbosity -ge 3 ] && echo "[WARNING] $@" || true
+}
+
+
+log_info()
+{
+    [ $verbosity -ge 4 ] && echo "[INFO] $@" || true
+}
+
+
+log_debug()
+{
+    [ $verbosity -ge 5 ] && echo "[DEBUG] $@" 1>&2 || true
+}
+
+
+log_error_exit()
+{
+    local returncode=$1
+    shift
+
+    log_error $@
+    exit $returncode
+}
+
+
+usage()
+{
+    echo "Usage: $(basename $0) [OPTION]..." 1>&2
+    echo "Install the latest version of this system's image to the alternate partition." 1>&2
+    echo 1>&2
+    echo "  -h, --help                       display this help message and exit" 1>&2
+    echo "  -v LEVEL, --verbosity LEVEL      set logging verbosity to LEVEL, default 4" 1>&2
+    echo "                                   range: 0-5, verbosity increases with value" 1>&2
+    echo "  -pa DEVICE, --partition-a DEVICE use DEVICE as the currently active partition" 1>&2
+    echo "  -pb DEVICE, --partition-b DEVICE use DEVICE as the partition to install the image to" 1>&2
+}
+
+
+###
+###
+###
+
+
+# Constants.
 image="image.img"
+image_type="${image##.}"
 image_gpg="${image}.gpg"
 
+
+# Default parameters.
+verbosity=4
+
+hostname=$(hostname -f)
+
+partition_a=$(mount -l | grep "^[^[:space:]]* on / " | awk '{ print $1 }')
+# partition_b=
+
+# grub_default_a=
+# grub_default_b=
+
+
+# Read arguments.
+while [ $# -ge 1 ]
+do
+    case "${1}" in
+        -h|--help) usage; exit 1;;
+        -v|--verbosity) verbosity="${2}"; shift 2;;
+        -pa|--partition-a) partition_a="${2}"; shift 2;;
+        -pb|--partition-b) partition_b="${2}"; shift 2;;
+        -gda|--grub-default-a) grub_default_a="${2}"; shift 2;;
+        -gdb|--grub-default-b) grub_default_b="${2}"; shift 2;;
+        *) usage; exit 1;;
+    esac
+done
+
+
+# Startup logging.
+log_info "${name} version ${version}"
+log_info
+log_debug "verbosity: ${verbosity}"
+log_debug "hostname: ${hostname}"
+log_debug "partition_a: ${partition_a}"
+log_debug "partition_b: ${partition_b}"
+log_debug "grub_default_a: ${grub_default_a}"
+log_debug "grub_default_b: ${grub_default_b}"
+log_debug
+
+
+# Runtime variables.
 tmp_dir=$(mktemp -d --suffix="${name}.XXXXXXXXXX")
 
-partition_a=""
-partition_b=""
-
 wget_args="-t 5 -T 30 --progress=dot"
+wget_repository=""
 
-dd_bs="1M"
+dd_bs="128K"
 
 mkfs_type="ext4"
 
@@ -26,26 +132,41 @@ grub_default_a=$(grep "^[:space:]*GRUB_DEFAULT=" /etc/default/grub | sed "s/^[:s
 
 
 # Download the image for this machine, and verify its integrity.
-while [ ! -f "${tmp_dir}/${image}" ] || \
-    gpg --verify "${tmp_dir}/${image}" "${tmp_dir}/${image_gpg}" > /dev/null 2>&1
+log_info "downloading image"
+
+while true
 do
-    wget ${wget_args} "${repository_url}/${hostname}/${image}" -O "${tmp_dir}/image.img"
-    wget ${wget_args} "${repository_url}/${hostname}/${image_gpg}" -O "${tmp_dir}/image.img.gpg"
+    wget ${wget_args} "${wget_repository}/${hostname}/${image}" -O "${tmp_dir}/${image}"
+    wget ${wget_args} "${wget_repository}/${hostname}/${image_gpg}" -O "${tmp_dir}/${image}"
+
+    log_info "verifying image"
+    if gpg --verify "${tmp_dir}/${image}" "${tmp_dir}/${image_gpg}" > /dev/null 2>&1
+    then
+        break
+    else
+        log_info "image verification failed, redownloading image"
+    fi
 done
 
 
-# dd
-dd if="${image}" of="${partition_b}" bs="${dd_bs}"
-
-
-# or mkfs/untar, depending on whether the downloaded file is an image or tarball
-mkfs -t "${mkfs_type}" "${partition_b}"
-mount -t "${mkfs_type}" "${partition_b}" "${tmp_dir}/root"
-tar -zxf "${tmp_dir}/image.tar.gz" "${tmp_dir}/root"
+# Install the image to a disk partition.
+if [ "${image_type}" = "img" ]
+then
+    log_info "installing image using dd"
+    dd if="${image}" of="${partition_b}" bs="${dd_bs}"
+elif [ "${image_type}" = "tar.gz" ]
+then
+    log_info "installing image using mkfs/tar"
+    mkfs -t "${mkfs_type}" "${partition_b}"
+    mount -t "${mkfs_type}" "${partition_b}" "${tmp_dir}/root"
+    tar -zxf "${tmp_dir}/${image}" "${tmp_dir}/root"
+    umount -l "${tmp_dir}/root"
+fi
 
 
 # update-grub
 # /etc/default/grub for Debian/Ubuntu
+log_info "configuring GRUB"
 cat > /etc/default/grub << ETC_DEFAULT_GRUB
 # If you change this file, run 'update-grub' afterwards to update
 # /boot/grub/grub.cfg.
@@ -81,7 +202,7 @@ GRUB_CMDLINE_LINUX=""
 
 # Uncomment to get a beep at grub start
 #GRUB_INIT_TUNE="480 440 1"
-
 ETC_DEFAULT_GRUB
 
+log_info "updating GRUB"
 update-grub -y
